engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
      ignore_warnings: true
    checks:
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,codesize,naming"
    checks:
      Naming/ShortVariable:
        enabled: false
  eslint:
    enabled: true

ratings:
  paths:
  - "**.php"
  - "**.js"
